apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-svc
  labels:
    app: nginx-demo
spec:
  selector:
    app: nginx-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # Use ClusterIP by default. Change to NodePort if you want external access:
  type: ClusterIP
